### ISSUE TITLE
possible issues with bump(Up|Down)ColumnName() ?

### ISSUE THREAD

**Issue by theycallmeroger** [s7/scale7-pelops#1]
Pelops is a great tool!  I really enjoy using it.  I came across the following issue.  I may be wrong, but I wanted to bring it to your attention and get your feedback.

The bumpUp/bumpDown behavior for several OrderTypes appears to be incorrect.  

(1) Consider the following column names when using OrderType.BytesType:

```
byte[] A = {0, 255};
byte[] B = {1, 0};
byte[] C = {1, 1};
byte[] D = {1, 255};
```

Cassandra compares these column names within org.apache.cassandra.db.marshal.BytesType using org.apache.cassandra.utils.FBUtilities.compareByteArrays(), such that: A < B < C < D.

Clearly, the "next" value after A is B; and the "next" value after B is C.

But when A is passed to org.scale7.cassandra.pelops.bumpUpColumnName(), it returns D instead of B.

Here is the current code:

```
for (int i=newName.length-1; i >= 0; i--) {
    if ((newName[i] & 0xFF) < 255) {
        newName[i] = (byte)((newName[i] & 0xFF) + 1);
        break;
     }
}
```

It should probably be changed to the following.  This same issue appears in multiple places in the code:

```
int i;
for (i=newName.length-1; i >= 0; i--) {
    newName[i] = (byte)((newName[i] & 0xFF) + 1);
    if (newName[i] != 0) {
        break;
     }
}
if (i < 0) {
    // input was all 0xFF's (or empty); is now all x00 (or empty); need to insert 0x01 at beginning.
    byte[] largerName = new byte[newName.length+1];
    largerName[0] = 1;
    System.arraycopy(newName, 0, largerName, 1, newName.length);
    newName = largerName;
}
```

(2) When using OrderType.TimeUIIDType, Cassandra compares these using org.apache.cassandra.db.marshal.TimeUUIDType, which according to java.util.UUID, assumes UUID variant=2 (Leach-Salz) and _requires_ UUID version=1 (time-based), or else an exception is thrown.

For the lower order long (last 8 bytes), bumpUpColumnName( ) should increment the bytes according to the change suggested above.  This will also increment the UUID variant, but that should be OK since it isn't checked/used elsewhere.

For the upper order order long (first 8 bytes), bumpUpColumnName() currently simply increments the entire Long value, which can increment the UUID version and result in an exception thrown by java.util.UUID.timestamp().  This should be changed to read the time with java.util.UUID.timestamp(), increment the time, and then write it back into the appropriate UUID bit fields without modifying the UUID version.

**Comment by danwashusen** [comment]
Nice writeup!

Would you be interested in submitting a patch (with tests) for these issues?

**Comment by theycallmeroger** [comment]
Thanks.  Sure I can write a patch with a few tests.  It may be a week or two before I can get to that, so if someone else wants to tackle it, fine with me.  I'm still using Cassandra 0.6.4 and an older version of Pelops from several weeks ago from your personal git site.  I plan to move to 0.7beta in 1-2 weeks, and after I do that, I can update to the latest Pelops and work on the patch.

**Comment by danwashusen** [comment]
I've changed the pagination code to no longer use the bump(Up|Down)ColumnName() methods.  As a result there are no more calls to bump(Up|Down)ColumnName() from within pelops.

I'm considering suggesting that we deprecate or remove the bump(Up|Down)ColumnName() methods and the broken pagination calls in favor of the new shiny (working and tested) methods.

So, are you using the bumpUpColumnName(), etc methods directly for something?

**Comment by theycallmeroger** [comment]
I agree with you. I'm in favor of deprecating bumpUp/Down instead of working to try to "fix" them.  I'm not using them directly, and was simply using them indirectly through the pagination interface.  I'm looking forward to updating to the latest version when I get a chance.

**Comment by danwashusen** [comment]
Fixed in trunk.  Deprecated bump methods and introduced new methods for pagination...

**Comment by tnine** [comment]
Hey Dan, which new methods were introduced to replace these?  I was using them for key paging with version 6.

**Comment by danwashusen** [comment]
Hey Todd,
There is no replacement for the bump methods.  They were broken and only being used by the pagination methods...

They've been deprecated for quite a while now...?

Cheers,
Dan
