### ISSUE TITLE
resurrection of columns of deleted rows after cassandra restart

### ISSUE THREAD

**Issue by mondkaefer** [s7/scale7-pelops#11]
pelops version: 0.907-0.7.0-SNAPSHOT
cassandra version: apache-cassandra-2010-10-14_12-30-38-bin.tar.gz
cluster: one cassandra node
consistency level: ALL

hi guys,

i create a row with a couple of columns in a column family of type standard.
i read all rows of the column family via selector.getColumnsFromRows(...) (note the 's' at the end of Rows).
the resulting map contains the columns of the newly created row just fine. i then delete that row using an instance of RowDeletor, and reads following the delete via selector.getColumnsFromRows(...) result in an empty column list for that row.
i guess that is how it should be.
however, if i then restart cassandra and read again via selector.getColumnsFromRows(...) , all the columns of the previously deleted row are there again, as if they had never been deleted. (the client cassandra-cli doesn't find any columns for that row anymore).

if i read the row via selector.getColumnsFromRow(...) (note the missing 's' at the end of Row), it works as expected, i.e. the column list is always empty for the deleted row, also in case of a cassandra restart.

i can consistently reproduce this behavior. happy to provide an example program, if you want.
is this a bug in selector.getColumnsFromRows(...), or a misunderstanding on my side?

thanks for feedback.

martin

p.s. same thing with pelops 0.903-0.7.0-SNAPSHOT and cassandra 0.7.0 beta1

**Comment by danwashusen** [comment]
I've had a look over the various getColumnsFromRows methods and can't see why Pelops would be causing this.  All the methods simply delegate to the org.apache.cassandra.thrift.Cassandra.Client#get_range_slices method and then iterate over the results...

Which of the getColumnsFromRows are you using?

I'd probably suggest posting your question over on the Cassandra mailing list to see if they can shed some light on it.  I'll chime in if they have any Pelops specific queries.  Make sure you've read http://wiki.apache.org/cassandra/FAQ#range_ghosts and http://wiki.apache.org/cassandra/DistributedDeletes first....

**Comment by mondkaefer** [comment]
thanks for the links, i'll have a look. i saw the distributed deletes page, but the odd thing is that the columns start showing up again upon restart of cassandra. anyhow, i guess i should have used an e-mail list first before opening an issue...

in my testing code i use the method like this:

```
int max = 100;
String cf = "user;
ConsistencyLevel cl = ConsistencyLevel.ALL;
KeyRange kr = Selector.newKeyRange("", "", max);
SlicePredicate sp = Selector.newColumnsPredicateAll(false, max);
Map<Bytes, List<Column>> userRows = selector.getColumnsFromRows(cf, kr, sp, cl);
```

(Using getColumnsFromRowsUtf8Keys(...) with the same params doesn't make a difference)

i worked my way around it for now, but i'll probably follow up on this on the cassandra e-mail  list.

thanks for the quick reply!

martin

**Comment by jsotelo** [comment]
Martin,

I've also noticed this and chalked it up to Cassandra beta-ness. How did you get around this and have you filed your ticket?

Javier

**Comment by danwashusen** [comment]
Putting this down to beta strangeness.
