### ISSUE TITLE
No unregister CachePerNodePoolMXBean on shutdown.

### ISSUE THREAD

**Issue by nikolajwestergaard** [s7/scale7-pelops#15]
CachePerNodePoolMXBean isn't unregistered during shutdown and CachePerNodePool does not check if CachePerNodePoolMXBean is registered on instantiation. This result in a Exception "exception while registering MBean, com.scale7.cassandra.pelops:type=CachePerNodePool-keyspace"  e.g. during reload of application using Listeners.

Unregister CachePerNodePoolMXBean during CachePerNodePool.shutdown() will solve this problem.

Thank you for a very nice library, and please continue the good work!

Best regard:
Nikolaj Westergaard
http://www.nwit.dk

**Comment by danwashusen** [comment]
Just published a new snapshot with a fix for this.  Could you please verify?

Thanks!

**Comment by nikolajwestergaard** [comment]
Looks good. Just tried out the new snapshot, works very fine.

Thanks!
