### ISSUE TITLE
Redundant functionality in Bytes.fromByteArray

### ISSUE THREAD

**Issue by YanivKunda** [s7/scale7-pelops#20]
Added in version 37792b3ab6a35fc8de86eb49eac47e472bc51d14, this method offers the same functionality as Bytes.fromBytes(byte[]) and the Bytes(bytes[]) constructor.
Its only use is, well, within Bytes.fromBytes(byte[])...

I believe it can be removed or at least deprecated - although I prefer the "fromByteArray" name better since the name of the class itself is "Bytes", and because it is goes better together with toByteArray.

**Comment by danwashusen** [comment]
Done (duplicate).
