### ISSUE TITLE
batch_mutate flush

### ISSUE THREAD

**Issue by brueckenc** [s7/scale7-pelops#3]
Flushing the connection causes the connection to close.  This is most easily observed by using a pool with just 1 connection.   batch_mutate has already flushed the connection and the seconds flush appears to not be necessary.

 public Void execute(IConnection conn) throws Exception {
                // Send batch mutation job to Thrift connection
                conn.getAPI().batch_mutate(convertedBatch, cLevel);
                // Flush connection
                conn.flush();
                // Nothing to return
                return null;
            }

**Comment by danwashusen** [comment]
Fixed in trunk.
