### ISSUE TITLE
Bytes data conversions do not support all ints, shorts, longs

### ISSUE THREAD

**Issue by dlvenable** [s7/scale7-pelops#34]
The Bytes data conversion methods do not support some possible cases. Integer column values stored from cassandra-cli can be fewer than 4 bytes long. When Bytes.toInt() is called in this case, the buffer will throw a BufferUnderflowException because there is only one element in the byte array, but the ByteBuffer is expecting 4 bytes.

The long and short conversions have a similar problem.

**Comment by danwashusen** [comment]
Any chance you could create a patch to fix this?

**Comment by dlvenable** [comment]
Yes, I can fix it.

**Comment by danwashusen** [comment]
I'll publish a new snapshot today.
