### ISSUE TITLE
Column Values cannot be null

### ISSUE THREAD

**Issue by andresilva** [s7/scale7-pelops#39]
The included Validator implements a behavior where column values cannot be set to null which isn't always desirable.

**Comment by danwashusen** [comment]
Cassandra doesn't accept null values (in fact it throws an exception that breaks the current connection).  If you want to mimic the behavior of a more traditional database I suggest turning on the org.scale7.cassandra.pelops.OperandPolicy#setDeleteIfNull property.  When Pelops detects a column with a null value it will substitute it with a delete (essentially making the column value null).

**Comment by andresilva** [comment]
I didn't know that Cassandra didn't allow null values, I thought it did. Sorry for bugging you and thanks for your help ;)

**Comment by danwashusen** [comment]
Happy to help! :)

Feel free to send any queries through the mailing list...
