### ISSUE TITLE
Bug with dynamicNodeDiscovery  in 1.2-0.8.x

### ISSUE THREAD

**Issue by eryabitskiy** [s7/scale7-pelops#44]
We are using 1.2-0.8.x and Cassandra 0.8.4.

And Pelops client is using dynamicNodeDiscovery feature. 

After migration to 0.8.4 we saw org.apache.thrift.transport.TTransportException in logs.

After debug I find out that it was thrown from this line:
 connection = (IPooledConnection) pool.borrowObject(node.getAddress());
and catch here:
https://github.com/s7/scale7-pelops/blob/scale7-pelops-1.2-0.8.x/src/main/java/org/scale7/cassandra/pelops/pool/CommonsBackedPool.java#L322

It happen because node.getAddress() return something like:   "host5.lan/192.168.1.5"
Where is host5.lan - is domain name in Intranet and 192.168.1.5 - is IP.

Current code is working like here should be only IP. Seems like format of Cassandra Thrift API describe_ring is changed and now it return endpoints in this format: host/ip.ip.ip.ip

Simple solution is to get substring from endpoint string (after '/') and use it as Node address.  

Update:
Found JIRA for it: https://issues.apache.org/jira/browse/CASSANDRA-1777
Not describe_ring return RpcaddressMap instead of EndpointMap to show topology, fixed at 0.8.4
So it's better to support back compatibility while fixing...

**Comment by danwashusen** [comment]
Thanks for reporting.  I'm not using dynamic node discovery in production - any chance you could submit a patch?

**Comment by eryabitskiy** [comment]
Yep. I will work on it at weekends.

**Comment by eryabitskiy** [comment]
Nice!
While I was going to submit a patch, I found out that bug is not reproducing on 0.8.5.
After https://issues.apache.org/jira/browse/CASSANDRA-3187 default format is compatible with current code again.
Closing issue.

**Comment by kvaster** [comment]
I'm still experiancing this problem with latest pelops code and cassandra 0.8.6...

**Comment by eryabitskiy** [comment]
I have checked over 0.8.5 and 0.8.6, dynamicNodeDiscovery works fine.

Are you using same thrift version as your installed cassandra?

 <dependency>
            <groupId>org.apache.cassandra</groupId>
            <artifactId>cassandra-thrift</artifactId>
            <version>0.8.6</version>
</dependency>

When your are using word "Latest" about lib version it's usually really confusing.

**Comment by kvaster** [comment]
Seems I missed something. I am very sorry for disturbing. I confirm all is working OK.

**Comment by musabbir-khan** [comment]
Hey guys, it seems that a lot of you went over this, but I am having this issue however.  Here are the versions that I am using -- 

Pelops - <doesn't say any version number>
Cassandra - cassandra-0.8.6
Thrift - apache-cassandra-thrift-0.8.6

Note: Not sure why the Pelops doesn't say any version number.  After downloading it i retrieved it from the "lib" folder without any version number.

I'm not using the dynamic node discovery, but here is my code -- 

```
    Pelops.addPool( "pool", new String[] { "localhost" }, 9160, false, "mykeyspace", new Policy() );
    Metrics metrics = Pelops.createMetrics( "pool" );
    return metrics.getKeyspaceSchema( "mykeyspace" );
```

When I execute the above 3 lines, on the third line I get some exceptions -- 

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.cassandra.thrift.Cassandra$Client.describe_keyspace(Ljava/lang/String;)Ljava/util/Map;
    at org.wyki.cassandra.pelops.Metrics$5.execute(Metrics.java:92)
    at org.wyki.cassandra.pelops.Operand.tryOperation(Operand.java:36)
    at org.wyki.cassandra.pelops.Metrics.getKeyspaceSchema(Metrics.java:95)

Any help would be greatly appreciated.  Thanks a bunch.

Khan

**Comment by danwashusen** [comment]
Khan, your issue is caused by a version mismatch...  Download the latest version of Pelops from https://github.com/s7/mvnrepo/tree/master/org/scale7/scale7-pelops

**Comment by musabbir-khan** [comment]
Thanks. Sorry for the late reply, but we put that project on shelf for now and everything kind of went the commercial product direction for now. Anyway, thanks again for your reply though.
