### ISSUE TITLE
Improve wrapping of exceptions from Cassandra Thrift

### ISSUE THREAD

**Issue by eryabitskiy** [s7/scale7-pelops#45]
In current implementation Pelops has wrappers for all Cassandra Thrift exceptions.

It will be much better to have all Exception information in stack trace. Current Thrift implementation return this info on getWhy().
And getMessage() return null. 
So it will be much better to use getWhy as message while wraaping:

```
public static class ExceptionTranslator implements IExceptionTranslator {
    @Override
    public PelopsException translate(Exception e) {
        if (e instanceof org.apache.cassandra.thrift.NotFoundException)
            return new NotFoundException(e);
```

....

chage to:

```
public static class ExceptionTranslator implements IExceptionTranslator {
    @Override
    public PelopsException translate(Exception e) {
        if (e instanceof org.apache.cassandra.thrift.NotFoundException)
            return new NotFoundException(e.getWhy(), e); // add getWhy() as message.
```

....

**Comment by danwashusen** [comment]
Good idea... can you submit a pull request with the suggested changes?

**Comment by eryabitskiy** [comment]
Not sure. I'm new with github... do I have authorization to manage requests? Don't see any available operations in "Pull requests" section.

But I am working on patch now ;)

**Comment by eryabitskiy** [comment]
It wasn't too hard! I have submit pull request with my changes.

What I didn't realize is how to attach pull request to this issue. So now there is 2 issues with same name. Should I close this one?

**Comment by danwashusen** [comment]
Merged!  Thanks for the patch.
