### ISSUE TITLE
touchNodeContext

### ISSUE THREAD

**Issue by brueckenc** [s7/scale7-pelops#5]
A host can be added twice to pool if hostname is used for initial list of nodes since other nodes are auto discovered by IP address.

**Comment by danwashusen** [comment]
Nice catch.  We'll have to convert the hostname to an IP address and merge that with the  auto discovered nodes or just replace initial list with the the auto discovered list.

**Comment by danwashusen** [comment]
Fixed in trunk but not yet published as a jar.

Thanks for reporting the issue!
