### ISSUE TITLE
Usage of microseconds instead of milliseconds for Cassandra timestamps

### ISSUE THREAD

**Issue by goossth** [s7/scale7-pelops#52]
Hi there,

First off--thank you for this well coded and tremendously useful library!

I was wondering whether the following improvement could be made. Currently Pelops uses System.currentTimeMillis() to generate its timestamps which are used in the Cassandra columns. Apparently three zeros are being appended to this number, to turn the figure into an approximation of the system microseconds. However, on most JVMs, more time accuracy is available through the System.nanoTime() call. Instead of adding three zeros to the number of milliseconds, in my opinion it would be better to strip three digits off the number of nanoseconds and use that for a timestamp.

Example:

1320405627458000 - example timestamp currently stored in Cassandra when using Pelops
1320405627458 - example output of System.currentTimeMillis()
1320405627458444000 - example output of System.nanoTime()
1320405627458444 - example timestamp that could be stored in Cassandra through the use of nanoTime()

In cases where I rely on the timestamp to decide which column was added later, this makes a material difference.

Many thanks,
Thomas

**Comment by danwashusen** [comment]
Hi Thomas,
We had looked at nanoTime but the Javadoc is pretty explicit about it's usefulness...

"The value returned represents nanoseconds since some fixed but arbitrary time (perhaps in the future, so values may be negative). This method provides nanosecond precision, but not necessarily nanosecond accuracy. No guarantees are made about how frequently values change."
- http://download.oracle.com/javase/6/docs/api/java/lang/System.html#nanoTime()

Were you thinking of a combination of currentTimeMillis & nanoTime?

Cheers,
Dan

**Comment by goossth** [comment]
Hi Dan,

Thank you for getting back to me so quickly. You are raising a couple of interesting points about nanoTime. It is indeed not as useful as I had hoped. It seems that nanoTime offers the precision I am looking for, but not the accuracy.

A combination of currentTimeMillis and nanoTime is an interesting thought, but I am a bit concerned about the performance. From what I've read, the nanoTime call is orders of magnitude more expensive than currentTimeMillis, and that does not even take into account all the calculations you would have to do in order to combine the two values into microseconds. The code would have to be robust enough to deal with nanoTime being unavailable or behaving erratically.

For what it's worth, here's a way you could combine the two figures into microseconds:

long currentTimeMillis = System.currentTimeMillis();
long nanoTime = System.nanoTime();
long currentTimeMicros = currentTimeMillis \* 1000 + nanoTime / 1000 - (nanoTime > 1000000 ? (nanoTime / 1000000) \* 1000 : 0);
System.out.println(currentTimeMicros);

Best regards,
Thomas
