### ISSUE TITLE
truncating a tablespace?

### ISSUE THREAD

**Issue by kostaskougios** [s7/scale7-pelops#65]
There doesn't seem to be a way to truncate a table space.

truncating can be useful i.e. during unit testing.

**Comment by danwashusen** [comment]
You can truncate a column family (org.scale7.cassandra.pelops.ColumnFamilyManager#truncateColumnFamily) or drop a keyspace (org.scale7.cassandra.pelops.KeyspaceManager#dropKeyspace).

There isn't a 'truncate keyspace' method available on the underlying thrift interface. Happy to take a look at a patch if you want to write up a convenience method...

**Comment by kostaskougios** [comment]
the functionality at ColumnFamilyManager was what I was looking for. Thanks, will close the issue
